### ISSUE TITLE
Major Lag Spikes In The Aether and Other Dimensions

### ISSUE THREAD

**Issue by GalaxyKitten42** [Rongmario/Gilded-Game-Util-Fix#1]
So this mod appealed to me since it got rid of the 'threaded lighting' feature, which back on the 1.7.10-1.9 version of Gilded Games Util, I kept getting weird lighting bugs usually when I broke blocks. I would break a block and a dark patch would be left in its place similar to what you'd find on world generation.

I downloaded this and replaced the gilded-games-util-1.7.10-1.9.jar with this and the lighting bugs where gone which was a relief. However upon entering the Aether and other dimensions, I started to get major lag spikes to the point where I'd be frozen in place for like 10 seconds or so, which never occurred on the 1.9 version. I have a pretty beefy computer and 5.1 GB of RAM allocated to my modpack so I really don't know why I'm getting these issues? Is there a way I could get the exact version of 1.9 of Gilded Games Util without the threaded lighting? Is there a way to disable it? Or does the removal of threaded lighting contribute to the lag spikes?

P.S I haven't tried the 1.10 or any of the other versions yet but I assume they are just going to be the same in terms of having threaded lighting.

**Comment by Rongmario** [comment]
Weird. It's been so long, but I don't recall there being any lag spikes. What Java installation are you using?

**Comment by GalaxyKitten42** [comment]
I am currently using Java 8 64-Bit for my Minecraft modpack, since I was told it was the recommended version for 1.7.10. I also use MultiMC to create multiple instances and so I created another Minecraft modpack with just Aether 2 and Gilded Games Util 2.0 installed and tried that too see if it was any different. And I still got lag spikes unfortunately. Just out of curiosity, (and since I'm a noob) is there a line of code in the gilded-games-util-1.7.10.1.9.jar file I could delete (via notepad) in order to get rid of that buggy threaded lighting?

P.S Also sorry for all the edits on my first post. I tend to have OCD when it comes to my grammar, and sorry for posting on an old repository.

**Comment by Rongmario** [comment]
I didn't do much to affect anything else compared to 1.9. Which makes it even more weird.

**Comment by Rongmario** [comment]
And no, unfortunately its not something a simple text fix could fix...

**Comment by GalaxyKitten42** [comment]
Ah I see. Could it be a possibility that maybe the forge version I'm using (10.13.4.1558-1.7.10) could be the culprit to causing these issues? May I ask, what forge version did you use to test the mod with? 

Also, why was threaded lighting even a thing in the first place do you reckon? Because I didn't see much difference with or without it apart from them lighting bugs I got when I had Gilded Games installed. Could the removal of threaded lighting be the reason for the lag spikes by any chance?

**Comment by Rongmario** [comment]
@GalaxyKitten42 sorry for the late reply, threaded lighting was an experimental thing that never made out of alpha.

Also I advise use .1614, its the best and latest build on 1.7.10.

**Comment by GalaxyKitten42** [comment]
Hello again, I know it's been a while. But I was just letting you know that I still get lag spikes with forge version .1614.  

I did some research about my current PC specs and I do have a possible culprit and that maybe my CPU, since my CPU is just over 10 years old (Intel Core i5-2500K 3.3 GHz). I was wondering if that probably would've caused the lag spikes in the Aether as well as on other occasions? I am planning on upgrading my CPU to an Intel Core i9-9900 as well as upgrade my RAM from DDR3 1333MHz (5GB allocated) to DDR4 3200MHz (8GB allocated). I was just wondering if this may play a significant improvement in terms of performance especially when I have a modpack with over 50 mods. Still unsure on how I got lag spikes on the fixed version and not the 1.9 version though. Then again I always still had the occasional lag spikes and jitters even with 1.9, it's just when I updated it to this one it went worse.

P.S I have also noticed that this fix is in the Project Ozone 2 modpack. I was wondering what the system requirements where for that modpack CPU and RAM wise? Especially, since that modpack has 100+ more mods in it than mine and still a lot of people play it without a problem.

**Comment by Rongmario** [comment]
It depends. Project Ozone 2 is already very heavy to run, an i9 9900 would do a lot better than a 2500k for sure though.

Minecraft just isn't optimized enough and its hard to tell what really was giving you lag spikes.

**Comment by GalaxyKitten42** [comment]
No worries, I am planning on installing FastCraft in future after I upgrade all my PC parts. That should hopefully sort it.

Just out of curiosity, and forgive me it may sound like I am asking the same question twice to some extent. When you developed/tested this mod, did you notice any performance difference between the two versions? I assume you have a better CPU than mine haha.

**Comment by Rongmario** [comment]
> Did you notice any performance difference between the two versions?.

Yes, but not by much.
